spring:
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/
    username: postgres
    password: postgres
  flyway:
    url: jdbc:postgresql://localhost:5432/
    user: postgres
    password: postgres